name: Publish latest version to pypi
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**'

jobs:
  generate-version:
    name: "Generate version"
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - name: "Checkout Action"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Git Version
        id: version
        uses: codacy/git-version@2.5.4
        with:
          minor-identifier: 'feat:'

      - id: tag
        run: echo "::set-output name=tag::${{ steps.version.outputs.version }}"

  build:
    name: "Build pip package"
    runs-on: ubuntu-latest
    needs:
      - generate-version

    steps:
      - name: "Checkout Action"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Set version to pytoml"
        uses: ciiiii/toml-editor@1.0.0
        with:
          file: "pyproject.toml"
          key: "tool.poetry.version"
          value: ${{ needs.generate-version.outputs.tag }}

      - name: "Set version to __init__.py"
        run: |
          echo "__version__ = '${{ needs.generate-version.outputs.tag }}'" > tdmctl/__init__.py

      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.12
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}